models/Facturas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "facturas".
 *
 * @property int $id
 * @property int|null $parte
 * @property int|null $factura
 * @property string|null $fecha
 * @property int|null $tipoiva
 * @property float|null $iva
 * @property float|null $subtotal
 * @property float|null $total
 *
 * @property Parte1 $parte0
 */
class Facturas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'facturas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['parte', 'factura', 'tipoiva'], 'integer'],
            [['fecha'], 'safe'],
            [['iva', 'subtotal', 'total'], 'number'],
            [['comentarios'], 'string'],
            [['parte'], 'exist', 'skipOnError' => true, 'targetClass' => Parte1::className(), 'targetAttribute' => ['parte' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parte' => 'Parte',
            'factura' => 'Factura',
            'fecha' => 'Fecha',
            'tipoiva' => 'Tipoiva',
            'comentarios' => 'Comentarios',
            'iva' => 'Iva',
            'subtotal' => 'Subtotal',
            'total' => 'Total',
        ];
    }

    /**
     * Gets query for [[Parte0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getParte0()
    {
        return $this->hasOne(Parte1::className(), ['id' => 'parte']);
    }
   public function getPartes()
    {
    return $this->hasMany(Parte1::className(), ['id' => 'parte']);
}

    public function getVehiculo0()
    {
        return $this->hasMany(Vehiculos::className(), ['id' => 'vehiculo'])
                ->viaTable('{{%parte1}}', ['vehiculo' => 'id']);
    }
    
        public function getCliente()
    {
        $query = UserComment::find();
        $query->leftJoin('user_comment_user',      'user_comment_user.user_comment_id=user_comment.id');
        $query->where(['receiver_id'=>$this->id, 'sender_id'=>$id]);
        $query->orWhere(['receiver_id'=>$id, 'sender_id'=>$this->id]);
        $query->orderBy(['created_at'=>SORT_DESC]);

        return $query;
    }
    
    public function afterFind() {
     parent::afterFind();
      if($this->fecha != Null){
         $this->fecha=Yii::$app->formatter->asDate($this->fecha, 'php:d-m-Y');
      }   
    }
    public function beforeSave($insert) {
        parent::beforeSave($insert);
        //$this->entrada=Yii::$app->formatter->asDatetime($this->entrada, 'php:Y-m-d H:i:s');
        //$this->salida=Yii::$app->formatter->asDatetime($this->salida, 'php:Y-m-d H:i:s');


         if($this->fecha != Null){
          $this->fecha=Yii::$app->formatter->asDate($this->fecha, 'php:Y-m-d');

        return parent::beforeSave($insert);

      }
    }
    
}

controllers/FacturasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Facturas;
use app\models\FacturasSearch;
use app\models\parte1;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\data\SqlDataProvider;
/**
 * FacturasController implements the CRUD actions for Facturas model.
 */
class FacturasController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Facturas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FacturasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Facturas model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Facturas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Facturas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Facturas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            
            $busco_parte = parte1::findOne($model->parte);

            $busco_parte->nfactura = $model->factura;
            $busco_parte->salida = $model->fecha;
            $busco_parte->save();
            
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Facturas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($factura)
    {
       $factura_eliminar = $this->findModel($factura);

       
       $model = new Facturas();
       
        $ultimaFactura= Facturas::find()
                        ->max('factura');   
                    
        if(empty($ultimaFactura) or $ultimaFactura == 0){
            $model->factura = 1;
        }else{    
            $model->factura = $ultimaFactura + 1;
        }
       $model->parte = $factura_eliminar->parte;
       $model->fecha = date("Y-m-d");
       $model->tipoiva = $factura_eliminar->tipoiva;
       $model->iva = $factura_eliminar->iva * -1;
       $model->subtotal = $factura_eliminar->subtotal * -1;
       $model->total = $factura_eliminar->total * -1;
       $model->comentarios = "Esta factura anula la ".$factura_eliminar->factura;
       $model->save();
       return $this->redirect(['index']);
    }

    /**
     * Finds the Facturas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Facturas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Facturas::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    
      public function actionFacturar()
    {
          $model = new Facturas();
 
          
         if (Yii::$app->request->post('idparte')){
             
             //Calculamos si las facturas va correlativas o hay algun salto
             //Si lo hay proseguimos con la numeración correlativa
            //$ultimaFactura= Facturas::find()
              //              ->max('factura');   
             $todas_facturas = Facturas::find()
                                ->select('factura')
                                ->asArray()
                                ->orderBy('factura asc')
                                ->all();
             
             
            foreach ($todas_facturas as $key => $value) { 
               // echo("Indice: ".$key." Valor: ".$value['factura']);
                
                if($key == 0 ){
                    $anterior = $value['factura'];
                }else{
                    if($value['factura'] == $anterior + 1){
                        $anterior = $value['factura'];
                    }else{    
                        $ultimaFactura = $anterior;
                    }
                }
            }
             
            if(empty($ultimaFactura) or $ultimaFactura == 0){
                $model->factura = 1;
            }else{    
                $model->factura = $ultimaFactura + 1;
                 //acualizamos el registro de parte asignandole la nueva factura generada
                $model_parte1 = new parte1();
                $actualizar_nfactura = $model_parte1->findOne(Yii::$app->request->post('idparte'));
                $actualizar_nfactura->nfactura =  $model->factura;
                $actualizar_nfactura->save();
            }
          
           
          
            $model->parte =  Yii::$app->request->post('idparte');
            //$base = Yii::$app->request->post('basefactura');          
            $model->tipoiva =  Yii::$app->request->post('tipoiva');
            $model->subtotal = Yii::$app->request->post('subtotal');
            $model->iva = Yii::$app->request->post('ivafactura');
            $model->total = Yii::$app->request->post('totalfactura');
            $model->fecha = Yii::$app->request->post('fechasalida');
            $model->save();
            return $this->redirect(['index']);
         }
         //$datos= array(['parte'=>$parte,'base'=>$base,'tipo_iva'=>$tipoIva,'subtotal'=>$subtotal,'iva'=>$iva,'total'=>$total]);
        //return json_encode($datos);
      
    }
    
    public function actionFacturacion(){
        //SELECT SUM(total) as total, DATE_FORMAT(fecha,'%M','en-es')as mes FROM facturas WHERE YEAR(fecha) = 2021 GROUP BY month(fecha)
        $anyo = $_POST['anyo'];
    
        $data = new SqlDataProvider([
                'sql' => 'SELECT SUM(total)as total, month(fecha) as mes FROM facturas WHERE YEAR(fecha) ='. $anyo.' GROUP BY month(fecha)',
        
        ]);
//        
//        $data = Facturas::find()
//                ->select('fecha', 'total')
//                ->from('facturas')
//                ->where(['Year(fecha)' => $anyo])
//                ->groupBy(['fecha'])
               // ->asArray()
//                ->all();
        $array_datos = $data->getModels();
//        var_dump($array_datos[0]['mes']);
//        exit;
//        
//        return($data);
//        exit;
     
        foreach ($array_datos as  $key => $value) {
           $array_datos[$key]['mes'] = $this->TraducirMes($value['mes']); 
        }

        $datos = JSON::encode($array_datos);
        return $datos;
    }
    
      public function actionEnviarfacturas()
    {
          
           $html = '
                <html lang="en">
                <head>
                        <meta charset="UTF-8">
                        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
                        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
                        <title>Envio correo Facturación</title>
                        <style type="text/css">


                        </style>
                </head>
                <body style="max-width:1200px;">    

                <header width="100%" align="center">
                       
                        <label style="padding:40px 100px 40px 100px; font-weight: bold;font-size:30px;">Taller JVidal</label>
                       
                       
                </header>

                <main width="100%" align="center">
                        <div style="text-align:center;color:#c62828;font-weight: bold;font-size:30px;">
                            <p style="">Resumen de Facturación </p>
                        </div>
                </main>

                <footer width="100%" align="center" style="margin-top:35px;">
                </footer>
                </body>
                </html>';
            
         $contenido = Yii::$app->mailer->compose();
           $destino = "robherblanc@gmail.com";
              // $contenido->attach($path.'/'.'lg_ayuntamiento.png');
                //->attach($path.'/'.'nif.jpg')
                //->attach($path.'/'.'firma.png')    
                //->attachContent('Contenido adjunto', ['fileName' => 'attach.txt', 'contentType' => 'text/plain'])
                $contenido->setTo($destino);
                $contenido->setFrom([Yii::$app->params['senderEmail']]);
                $contenido->setReplyTo([Yii::$app->params['senderEmail']]);

views/facturas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use dosamigos\datepicker\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Facturas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="facturas-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'parte')->textInput(['disabled' => true]) ?>

    <?= $form->field($model, 'factura')->textInput() ?>

    <?= $form->field($model, 'fecha')->widget(DatePicker::className(), [
        'language' => 'es',

        'inline' => false,
        'clientOptions' => [
            'autoclose' => true,
             'format' => 'dd-mm-yyyy',
            'clearBtn' => true,
            'todayBtn' => true
        ]
    ]);?>
    

    <?= $form->field($model, 'tipoiva')->textInput(['disabled' => true]) ?>

    <?= $form->field($model, 'iva')->textInput(['disabled' => true]) ?>

    <?= $form->field($model, 'subtotal')->textInput(['disabled' => true]) ?>

    <?= $form->field($model, 'total')->textInput(['disabled' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Anular',['facturas/delete','factura'=>$model->factura],['class' => 'btn btn-primary','data-method'=>'post','id'=>'anular_factura','style'=>'width:120px;']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/facturas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\FacturasSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="facturas-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'parte') ?>

    <?= $form->field($model, 'factura') ?>

    <?= $form->field($model, 'fecha') ?>

    <?= $form->field($model, 'tipoiva') ?>

    <?php // echo $form->field($model, 'iva') ?>

    <?php // echo $form->field($model, 'subtotal') ?>

    <?php // echo $form->field($model, 'total') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/facturas/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Facturas */

$this->title = 'Nueva Factura';
$this->params['breadcrumbs'][] = ['label' => 'Facturas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="facturas-create">

    

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/facturas/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\vehiculos;
use app\models\Parte1;
use app\models\Facturas;

/* @var $this yii\web\View */
/* @var $searchModel app\models\FacturasSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Facturas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="facturas-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Nueva Factura', ['create'], ['class' => 'btn btn-success','style'=>'background-color: #2395D1']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'parte',
            'factura',
            'fecha',
            'tipoiva',
            'iva',
            'subtotal',
            'total',
            'comentarios',

           ['class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                'contentOptions'=>[ 'style'=>'width: 100px;font-size:20px'],
            ],
        ],
    ]); ?>


</div>

views/facturas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Facturas */

$this->title = 'Registro: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Facturas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="facturas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/facturas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Facturas */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Facturas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="facturas-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'parte',
            'factura',
            'fecha',
            'tipoiva',
            'iva',
            'subtotal',
            'total',
        ],
    ]) ?>

</div>