models/Vehiculos.php
<?php

namespace app\models;

use Yii;
use app\models\Parte1;

/**
 * This is the model class for table "vehiculos".
 *
 * @property int $id
 * @property int|null $cliente
 * @property string|null $matricula
 * @property string|null $marca
 * @property string|null $color
 * @property string|null $bastidor
 * @property string|null $combustible
 *
 * @property Parte1[] $parte1s
 * @property Clientes $cliente0
 */
class vehiculos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'vehiculos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cliente'], 'integer'],
            [['matricula'], 'string', 'max' => 10],
            [['marca', 'combustible'], 'string', 'max' => 25],
            [['color'], 'string', 'max' => 20],
            [['bastidor'], 'string', 'max' => 17],
            [['cliente'], 'exist', 'skipOnError' => true, 'targetClass' => Clientes::className(), 'targetAttribute' => ['cliente' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cliente' => 'Cliente',
            'matricula' => 'Matricula',
            'marca' => 'Marca',
            'color' => 'Color',
            'bastidor' => 'Bastidor',
            'combustible' => 'Combustible',
        ];
    }

    /**
     * Gets query for [[Parte1s]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getParte1s()
    {
        return $this->hasMany(Parte1::className(), ['vehiculo' => 'id']);
    }

    /**
     * Gets query for [[Cliente0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCliente0()
    {
        return $this->hasOne(Clientes::className(), ['id' => 'cliente']);
    }
    
     public function getDuplicada($matricula)
    {
         if(vehiculos::findOne(['matricula'=>$matricula])){
            return true;
        }else{
            return false;
        }
    }
    public function getTiene_partes($vehiculo)
    {
         if(parte1::findOne(['vehiculo'=>$vehiculo])){
            return true;
        }else{
            return false;
        }
    }
}

controllers/Parte1Controller.php
<?php

namespace app\controllers;

use Yii;
use app\models\Parte1;
use app\models\Parte1Search;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * Parte1Controller implements the CRUD actions for Parte1 model.
 */
class Parte1Controller extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Parte1 models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new Parte1Search();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Parte1 model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Parte1 model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($vehiculo=NULL)
    {
        $model = new Parte1();
        
        $data_autocomplete = $model->getVehiculos_autocomplete();
        $repuestos_autocomplete = $model->getRepuestos_autocomplete();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        }else{
             $model->fecha_presupuesto = date('d-m-Y');
        }

        if (isset($vehivulo)){
            $model->vehiculo = $vehiculo;
          }
        return $this->render('create', [
            'model' => $model,
            'datos_autocomplete' => $data_autocomplete,
            'repuestos_autocomplete' => $repuestos_autocomplete,
        ]);
    }
  

    /**
     * Updates an existing Parte1 model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $repuestos_autocomplete = $model->getRepuestos_autocomplete();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'repuestos_autocomplete' => $repuestos_autocomplete,
        ]);
    }

    /**
     * Deletes an existing Parte1 model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Parte1 model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Parte1 the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Parte1::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/VehiculosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Vehiculos;
use app\models\VehiculosSearch;
use app\models\Clientes;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;

/**
 * VehiculosController implements the CRUD actions for Vehiculos model.
 */
class VehiculosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Vehiculos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VehiculosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Vehiculos model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Vehiculos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Vehiculos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Vehiculos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }
     public function actionUpdatemodal($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
           return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
        }

        return $this->renderPartial('update', [
            'model' => $model,
        ]);
    }
    

    /**
     * Deletes an existing Vehiculos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        
    //comprobamos si tiene algun parte de reparacion asignado
    $model_comprueba = new vehiculos();
    if($model_comprueba->getTiene_partes($id)){
        $mensaje = 'El Vehículo no se puede eliminar por que tiene partes de reparación asignados.';
        return $this->redirect(array('index?mensaje='.$mensaje));     
        //return $this->redirect(['index']);
    }
        
        $this->findModel($id)->delete();
//        if (Yii::$app->request->isAjax) {
//            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
//            return ['success' => true];
//        }
        return $this->redirect(['index']);
//       if (Yii::$app->request->post('modo') == 'pjax')
            
    }

    /**
     * Finds the Vehiculos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Vehiculos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Vehiculos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
     public function actionVehiculos_cliente()
    {
       
         
         $model = new vehiculos();
         
         if (Yii::$app->request->post('matricula')){
             
            $cliente = Yii::$app->request->post('cliente');
            $matricula = Yii::$app->request->post('matricula');
            $marca = Yii::$app->request->post('marca');
            $color = Yii::$app->request->post('color');
            $bastidor = Yii::$app->request->post('bastidor');
            $combustible = Yii::$app->request->post('combustible');
            
            $model->cliente = $cliente;
            $model->matricula = $matricula;
            $model->marca = $marca;
            $model->color = $color;
            $model->bastidor = $bastidor;
            $model->combustible = $combustible;
            
//            $model_cliente = new clientes();
//            $model_cliente->find()->where(['id' => $cliente]);
            
                                
          
            
            
            if(!$model->getDuplicada($matricula)){
                $model->save();
               
                $mensaje = "Vehículo Guardado";
                 
            }else{
                $mensaje = "Matricula ya existe";
             
            }
            
             $consulta = $model->find()
                ->where(['cliente'=>$cliente])
            //->andFilterWhere(['like', 'apellidos', $texto_buscar])
                ->orderBy(['id' => SORT_DESC]);
            
            $dataProvider = new ActiveDataProvider([
                'query' => $consulta,
                'pagination' => false,
            ]);               
                  
            return $mensaje;
        }
    }
    public function actionEliminar_pjax($id)
    {
        if (Yii::$app->request->post('cliente')){
            $cliente = Yii::$app->request->post('cliente');
            //comprobamos si tiene algun parte de reparacion asignado
            $model_comprueba = new vehiculos();
            if($model_comprueba->getTiene_partes($id)){
                $mensaje = 'El Vehículo no se puede eliminar por que tiene partes de reparación asignados.';
                return $this->redirect(array('clientes/update?id='.$cliente.'&mensaje='.$mensaje));         
            }
                           
            $this->findModel($id)->delete();
            return $this->redirect(['clientes/update?id='.$cliente]);
        }
    }
     public function actionDatos_cabecera($vehiculo = Null)
    {
        
       
        if (isset($vehiculo)){
            $consulta = vehiculos::find()
                ->from('vehiculos v')   
                ->select([
                    'nombre'=>'c.nombre',
                    'apellidos'=>'c.apellidos',
                    'localidad'=>'c.localidad',
                    'cif'=>'c.cif_nif',
                    'matricula'=>'v.matricula',
                    'marca'=>'v.marca',
                    'bastidor'=>'v.bastidor',
                     ])
                 ->innerJoin('clientes c', 'c.id = v.cliente')
                 ->where(['v.id'=>$vehiculo])
                ->asArray()
                ->all();
         
             //Yii::$app->response->format = Response::FORMAT_JSON;
            return json_encode($consulta);
           
        }
    }
    
}

views/vehiculos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Vehiculos */
/* @var $form yii\widgets\ActiveForm */
$tiposcombustible = ['Gasolina' => 'Gasolina', 'Diesel' => 'Diesel','Gas Natural' => 'Gas Natural','Bioetanol' => 'Bioetanol','Bioediesel' => 'Biodiesel','Biogás' => 'Biogás','Eléctrico' => 'Eléctrico','Hidrógeno' => 'Hidrógeno','Solar' => 'Solar',]; 
?>

<div class="vehiculos-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'cliente')->textInput() ?>

    <?= $form->field($model, 'matricula')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'marca')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'color')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'bastidor')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'combustible')->dropDownList($tiposcombustible); ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/vehiculos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\VehiculosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vehiculos-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'cliente') ?>

    <?= $form->field($model, 'matricula') ?>

    <?= $form->field($model, 'marca') ?>

    <?= $form->field($model, 'color') ?>

    <?php // echo $form->field($model, 'bastidor') ?>

    <?php // echo $form->field($model, 'combustible') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/vehiculos/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Vehiculos */

$this->title = 'Create Vehiculos';
$this->params['breadcrumbs'][] = ['label' => 'Vehiculos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vehiculos-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/vehiculos/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Clientes;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\models\VehiculosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Vehiculos';
$this->params['breadcrumbs'][] = $this->title;
$itemsApellidos =  ArrayHelper::map(Clientes::find()->select(['apellidos','id'])->asArray()->orderBy('apellidos')->all(),'apellidos', function ($model) {
                        return $model['apellidos'];
                        });
                        
if(isset($_REQUEST['mensaje'])){
    $mensaje = $_REQUEST['mensaje'];
}else{
    $mensaje ="";    
}                        
?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>
<div class="vehiculos-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
         <!--Html::a('Nuevo Vehiculo', ['create'], ['class' => 'btn btn-success'])--> 
          <span id ="msg" style="margin-left:200px;background-color: #2191c0;color:white;font-size:20px;border:solid 1px #EEE;border-radius:15px;padding:5px;display:none"><?=$mensaje?></span>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'cliente',
             [
              'label' => 'Nombre',
              'attribute' => 'filtro_nombre',
              'value' => 'cliente0.nombre',
              'filter' => ArrayHelper::map(Clientes::find()->all(), 'nombre','nombre'),
              'headerOptions' => ['style' => 'width:120px'],
              'enableSorting' => true,
            ],
            [
              'label' => 'Apellidos',
              'attribute' => 'filtro_apellidos',
              'value' => 'cliente0.apellidos',
              'filter' => $itemsApellidos,
              'enableSorting' => true,
              'headerOptions' => ['style' => 'width:150px;'],
            ],
            [
            'label' => 'Matricula',
            'attribute' => 'matricula',
            'value' => 'matricula',
            'headerOptions' => ['style' => 'width:120px;'],
            ],
            'marca',
            [
            'label' => 'Color',
            'attribute' => 'color',
            'value' => 'color',
            'headerOptions' => ['style' => 'width:100px;'],
            ],
            'bastidor',
            
             [
            'label' => 'Combustible',
            'attribute' => 'combustible',
            'value' => 'combustible',
            'headerOptions' => ['style' => 'width:120px;'],
            ],

            ['class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                 'contentOptions'=>[ 'style'=>'width: 100px;font-size:20px'],
                ],
              [
              'class' => 'yii\grid\ActionColumn',
              'template' => '{partes}',
              'contentOptions'=>['style'=>'width: 40px;font-size:20px'],
              'buttons' => [
              'partes' => function ($url, $model) {
                                  return Html::a('<span class="glyphicon glyphicon-wrench"></span>', $url, [
                                      'title' => Yii::t('app', 'Reparaciones'),
                                  ]);

                              }, 

                             ],

              'urlCreator' => function ($action, $model, $key, $index) {
                   return Url::to(['parte1/create', 'vehiculo' => $model->id]);
              }        

            ],
        ],
    ]); ?>


</div>


<script>
$( document ).ready(function() {
    
if($('#msg').html()!= ''){
     $("#msg").show();
   for(let i=0;i<5;i++){
            $("#msg").fadeToggle(1700);    
        }   
    $("#msg").fadeOut(); 
}     

    
});
</script>

views/vehiculos/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Vehiculos */

$this->title = 'Vehiculo: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Vehiculo', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="vehiculos-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/vehiculos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Vehiculos */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Vehiculos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="vehiculos-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Modificar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'cliente',
            'matricula',
            'marca',
            'color',
            'bastidor',
            'combustible',
        ],
    ]) ?>

</div>